version: 2.1

#orbs:
# android: circleci/android@0.2.0

executors:
  my-executor:
    docker:
      - image: circleci/android:api-29
    resource_class: xlarge

jobs:
  build:
    executor: my-executor
        
    steps:
      - checkout
      - run:
          command: ./gradlew build
