version: 2.1
# References are blocks of configurations that we can reference and reuse.
references:

  # Workspaces represent the spaces we work on & are useful for sharing data between jobs.
  # Create a workspace with the ~/code directory.
  workspace: &workspace
    ~/code
  # Docker Image Configs
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-29
      #resource class cannot use in free plan.
      #resource_class: medium+
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx3200m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx3200m"'
  # Cache - a cache mechanism for our dependencies
  gradle_key: &gradle_key
    v1-jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key
  save_gradle_cache: &save_gradle_cache
    save_cache:
      paths:
        - ~/code/.gradle
        - ~/code/.m2
      key: *gradle_key
  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *android_dependencies
      - *save_gradle_cache
      - run:
          name: Run gradle lint
          command: ./gradlew lint
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  build_and_test:
    <<: *android_config
    steps:
      - run:
          name: Run assembleDebug
          command: ./gradlew assembleDebug

workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build
      - build_and_test:
          requires:
            - build
